spring:
  datasource:
    url: "jdbc:mysql://localhost/library"
    username: "root"
    password: "dnjsdn1*"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        bytecode:
          show_sql: true
          format_sql: true
          dialect: org.hibernate.dialect.MYySQL8Dialect